drop table if exists air_company CASCADE;
drop table if exists air_plane CASCADE;
drop table if exists bank_card CASCADE;
drop table if exists ticket CASCADE;
drop table if exists user CASCADE;
--
create table air_company (id bigint generated by default as identity, country_location varchar(255), name_company varchar(255), primary key (id));
insert into air_company (id, country_location, name_company)
values
(null, 'Minsk', 'Belavia'),
(null, 'Moskva', 'Aeroflot'),
(null, 'London', 'Boing');
--
create table air_plane (id bigint generated by default as identity,  flight_date_end timestamp, flight_date_start timestamp, number_passanger integer, route_end varchar(255), route_start varchar(255), ticket_price integer, type varchar(255), air_company_id bigint, primary key (id));
insert into air_plane (id, flight_date_end, flight_date_start, number_passanger, route_end, route_start, ticket_price, type, air_company_id)
values
(null, '2022-07-03 14:00:00','2022-07-03 12:00:00', 6, 'Minsk', 'Moskva', 200, 'Boing747', 1),
(null, '2022-07-03 16:00:00','2022-07-03 14:00:00', 6, 'Minsk', 'London', 300, 'Boing747', 1),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'Minsk', 'Paris', 400, 'Boing747', 1),
(null, '2022-07-03 14:00:00','2022-07-03 12:00:00', 6, 'Moskva', 'Minsk', 500, 'Sukhoi Superjet 100', 2),
(null, '2022-07-03 16:00:00','2022-07-03 14:00:00', 6, 'Moskva', 'London', 600, 'Sukhoi Superjet 100', 2),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'Moskva', 'Paris', 700, 'Sukhoi Superjet 100', 2),
(null, '2022-07-03 14:00:00','2022-07-03 12:00:00', 6, 'London', 'Minsk', 800, 'Airbus A320', 3),
(null, '2022-07-03 16:00:00','2022-07-03 14:00:00', 6, 'London', 'Moskva', 900, 'Airbus A320', 3),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'London', 'Paris', 1000, 'Airbus A320', 3);
--
create table user (id bigint generated by default as identity, age bigint, category_client varchar(255), email varchar(255), is_active_profile boolean, lastname varchar(255), name varchar(255), passport_number varchar(255), phone integer, sex char(255), primary key (id));
insert into user (id, age, category_client, email, is_active_profile, lastname, name, passport_number, phone, sex)
values
(null, 23, 'VIP', 'abrakadabra@gmail.com', true, 'Yazvinski', 'Maksim', 'KK1100110', 998877, 'M'),
(null, 40, 'VIP', 'admin@gmail.com', true, 'Admin', 'Admin', 'KK1111111', 999999, 'M');
--
create table bank_card (id bigint generated by default as identity, bank ENUM('BELARUSBANK', 'BELINVESTBANK', 'PRIORBANK'),card_number bigint, card_type ENUM('VISA', 'MASTERCARD'), holder_lastname varchar(255), holder_name varchar(255), service_end_date timestamp, user_id bigint, primary key (id));
insert into bank_card (id, bank,card_number, card_type, holder_lastname, holder_name, service_end_date, user_id)
values
(null, 'BELARUSBANK', 1111222233334444, 'VISA', 'Yazvinski', 'Maksim', '2024-07-01 00:00:00', 1),
(null, 'BELINVESTBANK', 4444333322221111, 'MASTERCARD', 'Yazvinski', 'Maksim', '2024-07-01 00:00:00', 1),
(null, 'PRIORBANK', 1111222211112222, 'VISA', 'Admin', 'Admin', '2024-07-01 00:00:00', 2),
(null, 'BELINVESTBANK', 3333444433334444, 'MASTERCARD', 'Admin', 'Admin', '2024-07-01 00:00:00', 2);
--
create table ticket (id bigint generated by default as identity, is_active boolean, is_empty_seat boolean, passenger_seat integer, user_id bigint, air_plane_id bigint, primary key (id));
insert into ticket (id, is_active, is_empty_seat, passenger_seat, user_id, air_plane_id)
values
(null, true, false, 1, 1, 1),
(null, true, false, 2, 2, 1),
(null, true, true, 3, null, 1),
(null, true, true, 4, null, 1),
(null, false, true, 5, null, 1),
(null, false, true, 6, null, 1),
(null, true, false, 1, 1, 2),
(null, true, false, 2, 2, 2),
(null, true, true, 3, null, 2),
(null, true, true, 4, null, 2),
(null, false, true, 5, null, 2),
(null, false, true, 6, null, 2),
(null, true, false, 1, 1, 3),
(null, true, false, 2, 2, 3),
(null, true, true, 3, null, 3),
(null, true, true, 4, null, 3),
(null, false, true, 5, null, 3),
(null, false, true, 6, null, 3),
(null, true, false, 1, 1, 4),
(null, true, false, 2, 2, 4),
(null, true, true, 3, null, 4),
(null, true, true, 4, null, 4),
(null, false, true, 5, null, 4),
(null, false, true, 6, null, 4),
(null, true, false, 1, 1, 5),
(null, true, false, 2, 2, 5),
(null, true, true, 3, null, 5),
(null, true, true, 4, null, 5),
(null, false, true, 5, null, 5),
(null, false, true, 6, null, 5),
(null, true, false, 1, 1, 6),
(null, true, false, 2, 2, 6),
(null, true, true, 3, null, 6),
(null, true, true, 4, null, 6),
(null, false, true, 5, null, 6),
(null, false, true, 6, null, 6),
(null, true, false, 1, 1, 7),
(null, true, false, 2, 2, 7),
(null, true, true, 3, null, 7),
(null, true, true, 4, null, 7),
(null, false, true, 5, null, 7),
(null, false, true, 6, null, 7),
(null, true, false, 1, 1, 8),
(null, true, false, 2, 2, 8),
(null, true, true, 3, null, 8),
(null, true, true, 4, null, 8),
(null, false, true, 5, null, 8),
(null, false, true, 6, null, 8),
(null, true, false, 1, 1, 9),
(null, true, false, 2, 2, 9),
(null, true, true, 3, null, 9),
(null, true, true, 4, null, 9),
(null, false, true, 5, null, 9),
(null, false, true, 6, null, 9);


