create table flight_route (id bigint generated by default as identity, distance integer, flight_date_end timestamp, flight_date_start timestamp, is_active boolean, price integer, route_end varchar(255), route_start varchar(255), primary key (id));
insert into flight_route (id, distance, flight_date_end, flight_date_start, is_active, price, route_end, route_start)
values
(null, 1000, '2022-07-03 13:00:00','2022-07-03 12:00:00', true, 200, 'Moskva', 'Minsk'),
(null, 1000, '2022-07-03 17:00:00','2022-07-03 16:00:00', true, 200, 'Minsk', 'Moskva'),
(null, 2000, '2022-07-03 23:00:00','2022-07-03 20:00:00', true, 600, 'London', 'Minsk'),
(null, 2000, '2022-07-04 15:00:00','2022-07-04 12:00:00', true, 600, 'Minsk', 'London'),
(null, 2000, '2022-07-04 19:00:00','2022-07-04 16:00:00', true, 200, 'Paris', 'Minsk'),
(null, 2000, '2022-07-04 23:00:00','2022-07-04 20:00:00', true, 500, 'Minsk', 'Paris'),
(null, 2000, '2022-07-05 15:00:00','2022-07-05 12:00:00', true, 500, 'Paris', 'Minsk'),
(null, 3000, '2022-07-05 21:00:00','2022-07-05 16:00:00', true, 700, 'Moskva', 'Paris'),
(null, 3000, '2022-07-06 01:00:00','2022-07-05 20:00:00', true, 800, 'London', 'Moskva'),
(null, 3000, '2022-07-05 17:00:00','2022-07-05 12:00:00', true, 800, 'Moskva', 'London'),
(null, 3000, '2022-07-05 21:00:00','2022-07-05 16:00:00', true, 700, 'Paris', 'Moskva'),
(null, 1000, '2022-07-05 22:00:00','2022-07-05 20:00:00', true, 300, 'London', 'Paris');
