version: '3.3'

services:
  database:
    container_name: postgre
#    restart: on-failure
    image: postgres:14
    env_file:
      - web-db/database.env
    volumes:
      - ./web-db/secure.sql:/docker-entrypoint-initdb.d/secure.sql
      - ./web-db/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./web-db/data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


  data-base-app:
    container_name: data-base-app
    build: ./data-base-app
    image: data-base-app:data-base-app
    ports:
      - "8003:8003"
    environment:
      DB_URL: jdbc:postgresql://postgre:5432/myPostgreSQL
      DB_DRIVER: org.postgresql.Driver
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
    #    restart: on-failure
#    depends_on:
#      - web-db
 
  web-app:
    container_name: web-app
    build: ./web-app
    image: web-app:web-app
    ports:
      - "8001:8001"
    environment:
      DATA_BASE_APP_URL: http://data-base-app:8003/data-base-app
      DB_URL: jdbc:postgresql://postgre:5432/myPostgreSQL
      DB_DRIVER: org.postgresql.Driver
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_DIALECT: org.hibernate.dialect.PostgreSQL10Dialect
    depends_on:
#      - web-db
      - data-base-app
#    restart: on-failure



