create table ticket (id bigint generated by default as identity, is_active boolean, is_empty_seat boolean, passenger_seat integer, user_id bigint, air_plane_id bigint, primary key (id));
insert into ticket (id, is_active, is_empty_seat, passenger_seat, user_id, air_plane_id)
values
(null, true, false, 1, 1, 1),
(null, true, false, 2, 2, 1),
(null, true, true, 3, null, 1),
(null, true, true, 4, null, 1),
(null, false, true, 5, null, 1),
(null, false, true, 6, null, 1),

(null, true, false, 1, 1, 2),
(null, true, false, 2, 2, 2),
(null, true, true, 3, null, 2),
(null, true, true, 4, null, 2),
(null, false, true, 5, null, 2),
(null, false, true, 6, null, 2),

(null, true, false, 1, 1, 3),
(null, true, false, 2, 2, 3),
(null, true, true, 3, null, 3),
(null, true, true, 4, null, 3),
(null, false, true, 5, null, 3),
(null, false, true, 6, null, 3),

(null, true, false, 1, 1, 4),
(null, true, false, 2, 2, 4),
(null, true, true, 3, null, 4),
(null, true, true, 4, null, 4),
(null, false, true, 5, null, 4),
(null, false, true, 6, null, 4),

(null, true, false, 1, 1, 5),
(null, true, false, 2, 2, 5),
(null, true, true, 3, null, 5),
(null, true, true, 4, null, 5),
(null, false, true, 5, null, 5),
(null, false, true, 6, null, 5),

(null, true, false, 1, 1, 6),
(null, true, false, 2, 2, 6),
(null, true, true, 3, null, 6),
(null, true, true, 4, null, 6),
(null, false, true, 5, null, 6),
(null, false, true, 6, null, 6),

(null, true, false, 1, 1, 7),
(null, true, false, 2, 2, 7),
(null, true, true, 3, null, 7),
(null, true, true, 4, null, 7),
(null, false, true, 5, null, 7),
(null, false, true, 6, null, 7),

(null, true, false, 1, 1, 8),
(null, true, false, 2, 2, 8),
(null, true, true, 3, null, 8),
(null, true, true, 4, null, 8),
(null, false, true, 5, null, 8),
(null, false, true, 6, null, 8),

(null, true, false, 1, 1, 9),
(null, true, false, 2, 2, 9),
(null, true, true, 3, null, 9),
(null, true, true, 4, null, 9),
(null, false, true, 5, null, 9),
(null, false, true, 6, null, 9),

(null, true, false, 1, 1, 10),
(null, true, false, 2, 2, 10),
(null, true, true, 3, null, 10),
(null, true, true, 4, null, 10),
(null, false, true, 5, null, 10),
(null, false, true, 6, null, 10),

(null, true, false, 1, 1, 11),
(null, true, false, 2, 2, 11),
(null, true, true, 3, null, 11),
(null, true, true, 4, null, 11),
(null, false, true, 5, null, 11),
(null, false, true, 6, null, 11),

(null, true, false, 1, 1, 12),
(null, true, false, 2, 2, 12),
(null, true, true, 3, null, 12),
(null, true, true, 4, null, 12),
(null, false, true, 5, null, 12),
(null, false, true, 6, null, 12);



