create table bank_card (id bigint generated by default as identity, card_number bigint, user_profile_id bigint, primary key (id));
insert into bank_card (id, card_number, user_profile_id)
values
(null, 1111222233334444, 1),
(null, 4444333322221111, 1),
(null, 1111222211112222, 2),
(null, 3333444433334444, 2);