create table air_plane_flight_route (id bigint generated by default as identity, air_plane_id bigint, flight_route_id bigint, primary key (id));
insert into air_plane_flight_route (id, air_plane_id, flight_route_id)
values
(null, 1, 1),
(null, 1, 2),
(null, 1, 3);