create table air_company (id bigint generated by default as identity, country_location varchar(255), name_company varchar(255), primary key (id));
insert into air_company (id, country_location, name_company)
values
(null, 'Minsk', 'Belavia');