create table bank_card (id bigint generated by default as identity, card_number bigint, user_profile_id bigint, primary key (id));
insert into bank_card (id, card_number, user_profile_id)
values
(null, 1111222233334444, 1);