create table user_profile (id bigint generated by default as identity, email varchar(255), is_blocket_profile boolean, lastname varchar(255), username varchar(255), phone integer, user_id bigint, primary key (id));
insert into user_profile (id, email, is_blocket_profile, lastname, username, phone, user_id)
values
(null, 'admin@gmail.com', false, 'Admin', 'Admin', 999999, 2);