create table air_plane (id bigint generated by default as identity, number_seat integer, type varchar(255), air_company_id bigint, primary key (id));
insert into air_plane (id, number_seat, type, air_company_id)
values
(null, 6, 'Boing747', 1),
(null, 6, 'Boing747', 1),
(null, 6, 'Boing747', 1),
(null, 6, 'Sukhoi Superjet 100', 2),
(null, 6, 'Sukhoi Superjet 100', 2),
(null, 6, 'Sukhoi Superjet 100', 2),
(null, 6, 'Airbus A320', 3),
(null, 6, 'Airbus A320', 3),
(null, 6, 'Airbus A320', 3),
(null, 6, 'Airbus A320', 3),
(null, 6, 'Airbus A320', 3),
(null, 6, 'Airbus A320', 3);

