create table status (id bigint generated by default as identity, status varchar(255), primary key (id));
insert into status (id, status)
values
(null, 'PAID_FOR'),
(null, 'ORDERED'),
(null, 'CANCELLED');