create table user_order (id bigint generated by default as identity, is_active boolean, flight_route_id bigint, user_profile_id bigint, primary key (id));
insert into user_order (id, is_active, flight_route_id, user_profile_id)
values
(null, true, 1, 1),
(null, true, 1, 2);
