create table flight_route (id bigint generated by default as identity, distance integer, flight_date_end timestamp, flight_date_start timestamp, is_active boolean, route_end varchar(255), route_start varchar(255), primary key (id));
insert into flight_route (id, distance, flight_date_end, flight_date_start, is_active, route_end, route_start)
values
(null, 1000, '2022-07-03 14:00:00','2022-07-03 12:00:00', true, 'Moskva', 'Minsk'),
(null, 1000, '2022-07-03 18:00:00','2022-07-03 16:00:00', true, 'Minsk', 'Moskva'),
(null, 2000, '2022-07-03 22:00:00','2022-07-03 20:00:00', true, 'London', 'Minsk'),
(null, 2000, '2022-07-03 14:00:00','2022-07-03 12:00:00', true, 'Minsk', 'London'),
(null, 2000, '2022-07-03 18:00:00','2022-07-03 16:00:00', true, 'Paris', 'Minsk'),
(null, 2000, '2022-07-03 22:00:00','2022-07-03 20:00:00', true, 'Minsk', 'Paris'),
(null, 2000, '2022-07-03 14:00:00','2022-07-03 12:00:00', true, 'Paris', 'Minsk'),
(null, 3000, '2022-07-03 18:00:00','2022-07-03 16:00:00', true, 'Moskva', 'Paris'),
(null, 3000, '2022-07-03 22:00:00','2022-07-03 20:00:00', true, 'London', 'Moskva'),
(null, 3000, '2022-07-03 14:00:00','2022-07-03 12:00:00', true, 'Moskva', 'London'),
(null, 3000, '2022-07-03 18:00:00','2022-07-03 16:00:00', true, 'Paris', 'Moskva'),
(null, 1000, '2022-07-03 22:00:00','2022-07-03 20:00:00', true, 'London', 'Paris');