create table ticket (id bigint generated by default as identity, is_active boolean, passenger_profile_id bigint, seat_id bigint, user_order_id bigint, primary key (id));
insert into ticket (id, is_active, passenger_profile_id, seat_id, user_order_id)
values
(null, true, 1, 1, 1),
(null, true, 2, 2, 2);
