create table air_plane (id bigint generated by default as identity,  flight_date_end timestamp, flight_date_start timestamp, number_passanger integer, route_end varchar(255), route_start varchar(255), ticket_price integer, type varchar(255), air_company_id bigint, primary key (id));
insert into air_plane (id, flight_date_end, flight_date_start, number_passanger, route_end, route_start, ticket_price, type, air_company_id)
values
(null, '2022-07-03 14:00:00','2022-07-03 12:00:00', 6, 'Minsk', 'Moskva', 200, 'Boing747', 1),
(null, '2022-07-03 16:00:00','2022-07-03 14:00:00', 6, 'Minsk', 'London', 300, 'Boing747', 1),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'Minsk', 'Paris', 400, 'Boing747', 1),
(null, '2022-07-03 14:00:00','2022-07-03 12:00:00', 6, 'Moskva', 'Minsk', 500, 'Sukhoi Superjet 100', 2),
(null, '2022-07-03 16:00:00','2022-07-03 14:00:00', 6, 'Moskva', 'London', 600, 'Sukhoi Superjet 100', 2),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'Moskva', 'Paris', 700, 'Sukhoi Superjet 100', 2),
(null, '2022-07-03 14:00:00','2022-07-03 12:00:00', 6, 'London', 'Minsk', 800, 'Airbus A320', 3),
(null, '2022-07-03 16:00:00','2022-07-03 14:00:00', 6, 'London', 'Moskva', 900, 'Airbus A320', 3),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'London', 'Paris', 1000, 'Airbus A320', 3),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'Paris', 'London', 1000, 'Airbus A320', 3),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'Paris', 'Minsk', 1000, 'Airbus A320', 3),
(null, '2022-07-03 18:00:00','2022-07-03 16:00:00', 6, 'Paris', 'Moskva', 1000, 'Airbus A320', 3);
