create table user (id bigint generated by default as identity, age bigint, category_client varchar(255), email varchar(255), is_active_profile boolean, lastname varchar(255), name varchar(255), passport_number varchar(255), phone integer, sex char(255), primary key (id));
insert into user (id, age, category_client, email, is_active_profile, lastname, name, passport_number, phone, sex)
values
(null, 23, 'VIP', 'abrakadabra@gmail.com', true, 'Yazvinski', 'Maksim', 'KK1100110', 998877, 'M'),
(null, 40, 'VIP', 'admin@gmail.com', true, 'Admin', 'Admin', 'KK1111111', 999999, 'M');