--alter table if exists login_authorities drop constraint if exists FKm4ckh6v46sa0cnagqrndnjve3;
--alter table if exists login_authorities drop constraint if exists FKnpcdgiy8v7ivbgoit6la7je6a;
--drop table if exists authorities cascade;
--drop table if exists login cascade;
--drop table if exists login_authorities cascade;
--create table login_authorities (login_id int8 not null, authorities_id int8 not null);
--create table authorities (id int8 not null, name varchar(255), primary key (id));
--create table login (id int8 generated by default as identity, enabled boolean, password varchar(255), username varchar(255), primary key (id));
--alter table if exists login_authorities add constraint FKm4ckh6v46sa0cnagqrndnjve3 foreign key (authorities_id) references authorities;
--alter table if exists login_authorities add constraint FKnpcdgiy8v7ivbgoit6la7je6a foreign key (login_id) references login;
insert into authorities (id, name)
values
(1, 'USER'),
(2, 'MANAGER'),
(3, 'ADMIN');
commit;
insert into login (id, enabled, password, username)
values
(1, true, '$2a$12$bOVEohs92cz4EaRUWsiBJOzsLL4emLEkEEkQGw6UrMcFbsd8OJyHW', 'login'),
(2, true, '$2a$12$Xyy7tAjJWLIb3rf9j9uc4OfDsf5dsLKZjF/awksri1IzOZbha7cHi', 'manager'),
(3, true, '$2a$12$1Vjdo9ygapFpLjCvfCqHZeIGAkVhdlCaKpZnWK0ksrzQd4f01aR.q', 'admin');
commit;
insert into user_authorities (user_id, authorities_id)
values
(1,1),
(2,2),
(3,3);
commit;
