create table userProfile(
    id bigint generated by default as identity,
    primary key (id),
    username varchar_ignorecase(50) not null,
    password varchar_ignorecase(100) not null,
    enabled boolean not null
);
insert into userProfile (username, password, enabled)
values('guest','$2a$12$4NDtFM/kfBww5P4X8YJWIOVLRwzUmwP27aZyCFLIVvQcmBfCSxm1e', true);
insert into userProfile (username, password, enabled)
values('userProfile','$2a$12$4MPGlCa2T3P8ailm7D0SUOUaB1r5Fuk7L1gftw1.eI7bga6fMckBC', true);
insert into userProfile (username, password, enabled)
values('admin','$2a$12$Gi7Y0p0COJpRAg1khkvCn.jeLAWoqQACxdhR232mhBaTvJjSNGqum', true);
create table authorities (
    id bigint generated by default as identity,
    primary key (id),
    name varchar_ignorecase(50) not null
);
insert into authorities (name)
values('READER');
insert into authorities (name)
values('EDITOR');
insert into authorities (name)
values('AUTHOR');
create table USER_AUTHORITIES (
    user_id bigint,
    authorities_id bigint
);
insert into USER_AUTHORITIES (user_id, authorities_id)
values(1,1);
insert into USER_AUTHORITIES (user_id, authorities_id)
values(2,2);
insert into USER_AUTHORITIES (user_id, authorities_id)
values(3,3);
