drop table if exists authorities CASCADE;
drop table if exists login CASCADE;
drop table if exists user_authorities CASCADE;

create table authorities (id bigint not null, name varchar(255), primary key (id));
insert into authorities (id, name)
values
(1, 'USER'),
(2, 'MANAGER'),
(3, 'ADMIN');
create table login (id bigint generated by default as identity, enabled boolean, password varchar(255), username varchar(255), primary key (id));
insert into login (id, enabled, password, username)
values
(1, true, '$2a$12$bOVEohs92cz4EaRUWsiBJOzsLL4emLEkEEkQGw6UrMcFbsd8OJyHW','login'),
(2, true, '$2a$12$Xyy7tAjJWLIb3rf9j9uc4OfDsf5dsLKZjF/awksri1IzOZbha7cHi', 'manager'),
(3, true, '$2a$12$1Vjdo9ygapFpLjCvfCqHZeIGAkVhdlCaKpZnWK0ksrzQd4f01aR.q', 'admin');
create table user_authorities (user_id bigint not null, authorities_id bigint not null);
alter table user_authorities add constraint FKnfeejqie0sy3gxxil7dn3plsw foreign key (authorities_id) references authorities;
alter table user_authorities add constraint FKmj13d0mnuj4cd8b6htotbf9mm foreign key (user_id) references login;
insert into user_authorities (user_id, authorities_id)
values
(1,1),
(2,2),
(3,3);

