create table user(
    id bigint generated by default as identity,
    primary key (id),
    username varchar_ignorecase(50) not null,
    password varchar_ignorecase(100) not null,
    enabled boolean not null
);
insert into user (username, password, enabled)
values('user','$2a$12$bOVEohs92cz4EaRUWsiBJOzsLL4emLEkEEkQGw6UrMcFbsd8OJyHW', true);
insert into user (username, password, enabled)
values('manager',' $2a$12$Xyy7tAjJWLIb3rf9j9uc4OfDsf5dsLKZjF/awksri1IzOZbha7cHi', true);
insert into user (username, password, enabled)
values('admin','$2a$12$1Vjdo9ygapFpLjCvfCqHZeIGAkVhdlCaKpZnWK0ksrzQd4f01aR.q', true);

create table authorities (
    id bigint generated by default as identity,
    primary key (id),
    name varchar_ignorecase(50) not null
);
insert into authorities (name)
values('USER');
insert into authorities (name)
values('MANAGER');
insert into authorities (name)
values('ADMIN');
create table USER_AUTHORITIES (
    user_id bigint,
    authorities_id bigint
);
insert into USER_AUTHORITIES (user_id, authorities_id)
values(1,1);
insert into USER_AUTHORITIES (user_id, authorities_id)
values(2,2);
insert into USER_AUTHORITIES (user_id, authorities_id)
values(3,3);
